name: 'Setup Backend'
description: 'Checkout, install Python, and install backend dependencies with caching'

runs:
  using: 'composite'
  steps:
    - name: Read Python version
      id: python-version
      shell: bash
      run: echo "version=$(cat .python-version)" >> "$GITHUB_OUTPUT"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ steps.python-version.outputs.version }}
        cache: 'pip'
        cache-dependency-path: backend/requirements.txt

    - name: Cache Python packages
      uses: actions/cache@v4
      id: site-packages-cache
      with:
        path: |
          ${{ env.pythonLocation }}/lib/python*/site-packages
          ${{ env.pythonLocation }}/bin
        key: pip-v2-${{ runner.os }}-${{ steps.python-version.outputs.version }}-${{ hashFiles('backend/requirements.txt') }}

    - name: Install dependencies
      if: steps.site-packages-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
